#!/bin/bash

set -e

CATALINA_HOME=/usr/share/tomcat8-codedeploy

# Tar file name
TOMCAT8_CORE_TAR_FILENAME='apache-tomcat-8.0.52.tar.gz'
# Download URL for Tomcat7 core
TOMCAT8_CORE_DOWNLOAD_URL="http://mirrors.hust.edu.cn/apache/tomcat/tomcat-8/v8.0.52/bin/$TOMCAT7_CORE_TAR_FILENAME"
# The top-level directory after unpacking the tar file
TOMCAT8_CORE_UNPACKED_DIRNAME='apache-tomcat-8.0.52'


# Check whether there exists a valid instance
# of Tomcat7 installed at the specified directory
[[ -d $CATALINA_HOME ]] && { service tomcat8 status; } && {
    echo "Tomcat8 is already installed at $CATALINA_HOME. Skip reinstalling it."
    exit 0
}

# Clear install directory
if [ -d $CATALINA_HOME ]; then
    rm -rf $CATALINA_HOME
fi
mkdir -p $CATALINA_HOME

# Download the latest Tomcat8 version
cd /tmp
{ which wget; } || { yum install wget; }
wget $TOMCAT8_CORE_DOWNLOAD_URL
if [[ -d /tmp/$TOMCAT8_CORE_UNPACKED_DIRNAME ]]; then
    rm -rf /tmp/$TOMCAT8_CORE_UNPACKED_DIRNAME
fi
tar xzf $TOMCAT8_CORE_TAR_FILENAME

# Copy over to the CATALINA_HOME
cp -r /tmp/$TOMCAT8_CORE_UNPACKED_DIRNAME/* $CATALINA_HOME

# Install Java if not yet installed
{ which java; } || { yum install java; }

# Create the service init.d script
cat > /etc/init.d/tomcat8 <<'EOF'
#!/bin/bash
# description: Tomcat7 Start Stop Restart
# processname: tomcat7
PATH=$JAVA_HOME/bin:$PATH
export PATH
CATALINA_HOME='/usr/share/tomcat8-codedeploy'

case $1 in
start)
sh $CATALINA_HOME/bin/startup.sh
;;
stop)
sh $CATALINA_HOME/bin/shutdown.sh
;;
restart)
sh $CATALINA_HOME/bin/shutdown.sh
sh $CATALINA_HOME/bin/startup.sh
;;
esac
exit 0
EOF

# Change permission mode for the service script
chmod 755 /etc/init.d/tomcat8

